import Head from 'next/head'
import styles from '../styles/Map.module.css'
import MainNav from '../components/pages/MainNav'

import MainMap from '../components/map/MainMap'
import VariablePanel from '../components/map/VariablePanel'


// import useLoadData from '@webgeoda/hooks/useLoadData'
// import useUpdateData from '@webgeoda/hooks/useUpdateData'

import * as Comlink from 'comlink'

import rootReducer from '@webgeoda/reducers';
import { createStore } from 'redux';
import { Provider } from 'react-redux';
import { useEffect, useState } from 'react'

const store = createStore(rootReducer);
var geoda;

export default function Map() {
    const [geodaReady, setGeodaReady] = useState(false);

    useEffect(() => {
        geoda = Comlink.wrap(new Worker("./workers/worker.jsgeoda.js"))
        geoda.New().then(() => setGeodaReady(true)).then(() => geoda.listFunctions())
    },[])

    return (
        <div className={styles.container}>
            <Head>
                <title>Map :: WebGeoDa Template</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link
                rel="preconnect"
                href="https://fonts.gstatic.com"
                crossOrigin="true"
                />
                <link
                rel="preload"
                as="style"
                href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,900;1,400;1,700&family=Lora:ital@0;1&display=swap"
                />
                <link
                rel="stylesheet"
                href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,900;1,400;1,700&family=Lora:ital@0;1&display=swap"
                media="print"
                onLoad="this.media='all'"
                />
                <link href='https://api.mapbox.com/mapbox-gl-js/v2.2.0/mapbox-gl.css' rel='stylesheet' />
                <noscript>
                <link
                    rel="stylesheet"
                    href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,900;1,400;1,700&family=Lora:ital@0;1&display=swap"
                />
                </noscript>
            </Head>
            <MainNav/>
            
            <Provider store={store}>
                {geodaReady && 
                <>
                    <MainMap geoda={geoda} />
                    <VariablePanel />
                </>}
            </Provider>
        </div>
    )
}
