import Head from 'next/head'
import styles from '../styles/Map.module.css'
import MainNav from '../components/MainNav'
import MainMap from '../components/MainMap'

import JsGeoDaWorker from '@webgeoda/workers/JsGeoDaWorker'
// import useLoadData from '@webgeoda/hooks/useLoadData'
// import useUpdateData from '@webgeoda/hooks/useUpdateData'

const gdaProxy = new JsGeoDaWorker()

import rootReducer from '@webgeoda/reducers';
import { createStore } from 'redux';
import { Provider } from 'react-redux';
const store = createStore(rootReducer);

export default function Map() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Webgeoda Template</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link
                rel="preconnect"
                href="https://fonts.gstatic.com"
                crossOrigin="true"
                />
                <link
                rel="preload"
                as="style"
                href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,900;1,400;1,700&family=Lora:ital@0;1&display=swap"
                />
                <link
                rel="stylesheet"
                href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,900;1,400;1,700&family=Lora:ital@0;1&display=swap"
                media="print"
                onLoad="this.media='all'"
                />
                <link href='https://api.mapbox.com/mapbox-gl-js/v2.2.0/mapbox-gl.css' rel='stylesheet' />
                <noscript>
                <link
                    rel="stylesheet"
                    href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,900;1,400;1,700&family=Lora:ital@0;1&display=swap"
                />
                </noscript>
            </Head>
            <MainNav/>
            
            <Provider store={store}>
                <MainMap gdaProxy={gdaProxy} />
            </Provider>
        </div>
    )
}
